# version: '3.7'

# services:
#   backend:
#     volumes:
#       - static:/static
#     env_file:
#       - .env
#     build:
#       context: ./villager_chess
#     ports:
#       - "8000:8000"

version: '3.7'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static:/static
    networks:
      - dev
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=villager_server
      - POSTGRES_USER=sbyard
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./villager_chess_api/fixtures:/docker-entrypoint-initdb.d
    networks:
      - dev

volumes:
  static:
  postgres_data:

networks:
  dev:
# CHECK