from .chess_club_serializers import ChessClubSerializer, CreateChessClubSerializer
from .player_serializers import PlayerSerializer, CreatePlayerSerializer, PlayerOnClubSerializer, FriendSerializer, PlayerProfileSerializer, CommunityPosterSerializer
from .guest_player_serializers import GuestOnClubSerializer
from .community_post_serializers import CommunityPostSerializer, CreateCommunityPostSerializer