# Generated by Django 4.2.1 on 2023-05-31 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_amount', models.IntegerField()),
                ('increment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time_setting', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tournaments_with_time_setting', to='villager_chess_api.timesetting')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='followers', to='villager_chess_api.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='villager_chess_api.player')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='villager_chess_api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('w_notes', models.CharField(default='', max_length=100)),
                ('b_notes', models.CharField(default='', max_length=100)),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to='villager_chess_api.player')),
                ('player_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to='villager_chess_api.player')),
                ('time_setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='villager_chess_api.timesetting')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='villager_chess_api.tournament')),
            ],
        ),
    ]
