# Generated by Django 4.2.1 on 2023-06-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='datetime',
        ),
        migrations.AddField(
            model_name='game',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pgn',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='win_style',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='villager_chess_api.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='villager_chess_api.timesetting'),
        ),
    ]
