# Generated by Django 4.2.1 on 2023-06-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0002_remove_game_datetime_game_accepted_game_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
