# Generated by Django 4.2.1 on 2023-06-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0003_tournament_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='my_tournaments', to='villager_chess_api.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='villager_chess_api.tournament'),
        ),
    ]
