# Generated by Django 4.2.1 on 2023-06-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0005_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament_round',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
