# Generated by Django 4.2.1 on 2023-06-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0006_game_tournament_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='competitors',
            field=models.ManyToManyField(related_name='joined_tournaments', to='villager_chess_api.player'),
        ),
    ]
