# Generated by Django 4.2.1 on 2023-06-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0007_tournament_competitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
