# Generated by Django 4.2.1 on 2023-06-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0009_tournament_pairings_alter_game_b_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='in_person',
            field=models.BooleanField(default=False),
        ),
    ]
