# Generated by Django 4.2.1 on 2023-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0010_tournament_in_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bye',
            field=models.BooleanField(default=False),
        ),
    ]
