# Generated by Django 4.2.1 on 2023-06-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0011_game_bye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='b_notes',
        ),
        migrations.RemoveField(
            model_name='game',
            name='w_notes',
        ),
    ]
