# Generated by Django 4.2.2 on 2023-07-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0016_guestplayer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestplayer',
            old_name='name',
            new_name='full_name',
        ),
    ]
