# Generated by Django 4.2.2 on 2023-07-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0017_rename_name_guestplayer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='guest_competitors',
            field=models.ManyToManyField(related_name='joined_tournaments', to='villager_chess_api.guestplayer'),
        ),
    ]
