# Generated by Django 4.2.2 on 2023-07-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('villager_chess_api', '0018_tournament_guest_competitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_b',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_w',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='target_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='target_player_b_ct',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'Player'), ('model', 'GuestPlayer'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_b', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='game',
            name='target_player_w_ct',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'Player'), ('model', 'GuestPlayer'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_w', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='game',
            name='target_winner_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('model', 'Player'), ('model', 'GuestPlayer'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='contenttypes.contenttype'),
        ),
    ]
