# Generated by Django 4.2.2 on 2023-07-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0019_remove_game_player_b_remove_game_player_w_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='target_id',
            new_name='target_player_b_id',
        ),
        migrations.AddField(
            model_name='game',
            name='target_player_w_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='target_winner_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
