# Generated by Django 4.2.2 on 2023-07-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0020_rename_target_id_game_target_player_b_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=75, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=5, null=True)),
                ('zipcode', models.PositiveIntegerField(null=True)),
                ('details', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('guest_members', models.ManyToManyField(related_name='selected_guests_tournaments', to='villager_chess_api.guestplayer')),
                ('manager', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clubs', to='villager_chess_api.player')),
                ('members', models.ManyToManyField(related_name='my_clubs', to='villager_chess_api.player')),
            ],
        ),
        migrations.AddField(
            model_name='communitypost',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='villager_chess_api.chessclub'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='club_tournaments', to='villager_chess_api.chessclub'),
        ),
    ]
