# Generated by Django 4.2.2 on 2023-07-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0021_chessclub_guestplayer_club_player_clubs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestplayer',
            name='club',
        ),
        migrations.RemoveField(
            model_name='player',
            name='clubs',
        ),
        migrations.AlterField(
            model_name='chessclub',
            name='manager',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clubs', to='villager_chess_api.player'),
        ),
    ]
