# Generated by Django 4.2.2 on 2023-07-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villager_chess_api', '0022_remove_guestplayer_club_remove_player_clubs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='villager_chess_api.chessclub'),
        ),
    ]
